#### Pretrain

##### Настройка окружения

In [14]:
import os
import glob
import re
import nltk
import random
import pandas as pd
import numpy as np
from tqdm import tqdm
import accelerate
import jinja2
import hashlib
from difflib import SequenceMatcher

import torch
from sklearn.model_selection import train_test_split
from transformers import (
    PreTrainedTokenizerFast,
    AutoTokenizer,
    AutoModelForCausalLM,
    BitsAndBytesConfig,
    LlamaConfig,
    LlamaForCausalLM,
    Trainer,
    TrainingArguments,
    TrainerCallback,
    DataCollatorForLanguageModeling,
    EarlyStoppingCallback)

from datasets import Dataset, load_dataset

from tokenizers import Tokenizer
from tokenizers.models import BPE
from tokenizers.trainers import BpeTrainer
from tokenizers.pre_tokenizers import Whitespace

from trl import SFTTrainer, SFTConfig
from peft import LoraConfig, get_peft_model

In [3]:
def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

set_seed(42)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"using device: {device}")

using device: cuda

In [56]:
if not os.path.exists("RussianNovels"):
    !git clone https://github.com/JoannaBy/RussianNovels.git

file_paths = glob.glob('RussianNovels/corpus/*.txt')
print(f"Найдено файлов: {len(file_paths)}")

Найдено файлов: 108

In [57]:
# чтение файлов в 1 список
raw_texts = []
for file_path in file_paths:
    with open(file_path, 'r', encoding='utf-8') as f:
        try:
            text = f.read()
            raw_texts.append(text)
        except Exception as e:
            print(f"Ошибка чтения файла {file_path}: {e}")
            
print(f"Загружено текстов: {len(raw_texts)}")

Загружено текстов: 108

##### 1. Препроцессинг данных

In [58]:
nltk.download('punkt')
nltk.download('punkt_tab')

# фиксим кириллицу
def is_cyrillic(text):
    return not bool(re.search('[a-zA-Z]', text))

# фиксим пунктуацию
def clean_text(text):
    text = re.sub(r'\s+', ' ', text)
    text = re.sub(r'\s+([.,!?;:])', r'\1', text)
    text = re.sub(r'[,]{2,}', ',', text)
    text = re.sub(r'[!]{2,}', '!', text)
    text = re.sub(r'[?]{2,}', '?', text)
    text = re.sub(r'--+', '—', text)
    text = text.replace("—", " — ")
    text = re.sub(r'\s+', ' ', text)
    text = text.strip()
    return text

all_sentences = []

for text in tqdm(raw_texts):
    sentences = nltk.sent_tokenize(text, language='russian')
    
    for sent in sentences:
        sent = clean_text(sent)
        if len(sent) > 10 and is_cyrillic(sent):
            all_sentences.append(sent)
            
# фиксим дубликаты
orig_count = len(all_sentences)
uniq_sentences = list(set(all_sentences))
print(f"Предложений до очистки: {orig_count}")
print(f"Предложений после удаления дубликатов: {len(uniq_sentences)}")

[nltk_data] Downloading package punkt to /home/ubuntu/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /home/ubuntu/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
100%|██████████| 108/108 [00:17<00:00,  6.22it/s]

Предложений до очистки: 470932
Предложений после удаления дубликатов: 454666

In [59]:
# сборка в чанки
full_clean_text = " ".join(uniq_sentences)
chunk_size = 1400

chunks = [full_clean_text[i:i+chunk_size] for i in range(0, len(full_clean_text), chunk_size)]

print(f"Сформировано чанков: {len(chunks)}")

Сформировано чанков: 29369

##### 2. Обучение токенизатора

In [60]:
tokenizer = Tokenizer(BPE(unk_token="<unk>"))
tokenizer.pre_tokenizer = Whitespace()

trainer = BpeTrainer(
    vocab_size=3000, 
    special_tokens=["<bos>", "<eos>", "<unk>", "<pad>"],
    min_frequency=2
)

tokenizer.train_from_iterator(chunks, trainer)

tokenizer.save("custom_tokenizer.json")

fast_tokenizer = PreTrainedTokenizerFast(
    tokenizer_file="custom_tokenizer.json",
    bos_token="<bos>",
    eos_token="<eos>",
    unk_token="<unk>",
    pad_token="<pad>"
)

sample_text = "Велик был год и страшен год по рождестве Христовом 1918"
tokens = fast_tokenizer.encode(sample_text)
print(f"Пример токенизации: {fast_tokenizer.convert_ids_to_tokens(tokens)}")
print(f"Размер словаря: {fast_tokenizer.vocab_size}")

Пример токенизации: ['Ве', 'ли', 'к', 'был', 'год', 'и', 'стра', 'шен', 'год', 'по', 'ро', 'жде', 'стве', 'Хри', 'сто', 'вом', '1', '9', '1', '8']
Размер словаря: 3000

Собственный токенизатор (vocab=3000) гораздо эффективнее для этой задачи. Каждый токен будет встречаться достаточно часто, чтобы модель выучила его эмбеддинг. Использование BPE позволяет эффективно кодировать редкие слова через подслова.

##### 3. Подготовка данных к претрейну

In [61]:
context_length = 512

def tokenization_func(examples):
    # добавление bos, eos к тексту
    text_list = [fast_tokenizer.bos_token + t + fast_tokenizer.eos_token for t in examples['text']]
    
    # с обрезкой и паддингом
    return fast_tokenizer(
        text_list,
        truncation=True,
        max_length=context_length,
        padding="max_length"
    )
    
dataset = Dataset.from_dict({"text": chunks})

tokenized_dataset = dataset.map(
    tokenization_func,
    batched=True,
    num_proc=4,
    remove_columns=["text"]
)

# разбиваем на подвыборки
split_dataset = tokenized_dataset.train_test_split(test_size=.05)
train_dataset = split_dataset['train']
eval_dataset = split_dataset['test']

print(train_dataset)

Map (num_proc=4): 100%|██████████| 29369/29369 [00:08<00:00, 3373.84 examples/s]

Dataset({
    features: ['input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 27900
})

##### 4. Инициализация модели

In [62]:
config = LlamaConfig(
    vocab_size=fast_tokenizer.vocab_size,
    hidden_size=1024,
    intermediate_size=1536,
    num_hidden_layers=16,
    num_attention_heads=16,
    num_key_value_heads=8,
    max_position_embeddings=context_length,
    bos_token_id=fast_tokenizer.bos_token_id,
    eos_token_id=fast_tokenizer.eos_token_id,
    pad_token_id=fast_tokenizer.pad_token_id
)

model = LlamaForCausalLM(config)

# смотрим параметры
n_params = sum(p.numel() for p in model.parameters())
print(f"кол-во параметров модели: {n_params / 1e6:.2f}M")

кол-во параметров модели: 132.01M

##### 5. Обучение и валидация качества

In [63]:
test_prompts = [
    "Все мысли, которые имеют огромные последствия",
    "Сила войска зависит от его духа",
    "Мысль о том, что он принес страдания",
    "Человек сознает себя свободным",
    "Что бы ни случилось, я всегда буду",
    "Любовь мешает смерти",
    "Нет, жизнь не кончена",
    "Всякая мысль, даже самая простая",
    "Война не любезность, а самое гадкое дело",
    "Чтобы жить честно"
]

In [64]:
class GenerationCallback(TrainerCallback):
    # колбэк для генерации текста в процессе обучения чтобы видеть прогресс модели
    def __init__(self, tokenizer, model, prompts):
        self.tokenizer = tokenizer
        self.model = model
        self.prompts = prompts
        
    def on_evaluate(self, args, state, control, **kwargs):
        print("\n=== GENERATION LOG (Validation Phase) ===")
        device = next(self.model.parameters()).device
        self.model.eval()
        
        for prompt in self.prompts[:2]: 
            inputs = self.tokenizer(prompt, return_tensors="pt", return_token_type_ids=False).to(device)
            with torch.no_grad():
                outputs = self.model.generate(
                    **inputs, 
                    max_new_tokens=40, 
                    do_sample=True, 
                    temperature=0.6,
                    top_k = 50,
                    top_p = .95,
                    repetition_penalty=1.2,
                    no_repeat_ngram_size=2,
                    pad_token_id=self.tokenizer.pad_token_id,
                    eos_token_id=self.tokenizer.eos_token_id
                )
            raw_output = self.tokenizer.decode(outputs[0], skip_special_tokens=True)
            readable_output = raw_output.replace(" ", "")
            readable_output = readable_output.replace(",", ", ").replace(".", ". ").replace("!", "! ").replace("?", "? ").replace("—", " — ")
            generated_text = self.tokenizer.decode(outputs[0], skip_special_tokens=True)
            print(f"Input: {prompt}\nRaw_Output: {raw_output}\nReadable_output: {readable_output}\n")
        
        self.model.train()

training_args = TrainingArguments(
    output_dir="./russian_lit_model",
    overwrite_output_dir=True,
    num_train_epochs=15,
    per_device_train_batch_size=64,  
    per_device_eval_batch_size=64,    
    eval_strategy="steps", 
    eval_steps=250,
    save_steps=250,
    save_total_limit=1,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    load_best_model_at_end=True,
    logging_steps=100,
    learning_rate=1e-4,
    weight_decay=0.01,
    warmup_ratio=.1,              
    fp16=torch.cuda.is_available(), 
    report_to="none"
)

data_collator = DataCollatorForLanguageModeling(
    tokenizer=fast_tokenizer, 
    mlm=False
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    data_collator=data_collator,
    callbacks=[
        GenerationCallback(fast_tokenizer, model, test_prompts),
        EarlyStoppingCallback(early_stopping_patience=3)
    ]
    
)

trainer.train()
trainer.save_model("./russian_lit_model_final")
fast_tokenizer.save_pretrained("./russian_lit_model_final")

=== GENERATION LOG (Validation Phase) ===
Input: Все мысли, которые имеют огромные последствия
Raw_Output: Все мысли , которые име ют огром ные послед ствия по ший — сказал
Readable_output: Всемысли, которыеимеютогромныепоследствияпоший — сказал

Input: Сила войска зависит от его духа
Raw_Output: Си ла вой ска зави си т от его ду ха гах по чер з пы и , а с су х от ки : " – За х о сла пе ну . Я вы не от меня , что это при че в то , если я не су
Readable_output: Силавойсказависитотегодухагахпочерзпыи, ассухотки:"–Захослапену. Явынеотменя, чтоэтопричевто, еслиянесу


=== GENERATION LOG (Validation Phase) ===
Input: Все мысли, которые имеют огромные последствия
Raw_Output: Все мысли , которые име ют огром ные послед ствия и не вы ходит , как я на ле во му . — Она вас не при ш лось , что ли ? – Я не было бы и ничего не будет . - Это не знал , - сказал
Readable_output: Всемысли, которыеимеютогромныепоследствияиневыходит, какяналевому.  — Онаваснепришлось, чтоли? –Янебылобыиничегонебудет. -Этонезнал, -сказал

Input: Сила войска зависит от его духа
Raw_Output: Си ла вой ска зави си т от его ду ха под " их че х нь н ли ди х ми " з ц ! К ни не лов . — Как я только по сто па жи ! Я бы по ху ку х . Про ди че т
Readable_output: Силавойсказависитотегодухапод"ихчехньнлидихми"зц! Книнелов.  — Какятолькопостопажи! Ябыпохукух. Продичет


=== GENERATION LOG (Validation Phase) ===
Input: Все мысли, которые имеют огромные последствия
Raw_Output: Все мысли , которые име ют огром ные послед ствия , и , как не известно , с тем же со зда нным то ном , который он не мог понять , что это было и не в этом . — Что , конечно , не могу , ничего !
Readable_output: Всемысли, которыеимеютогромныепоследствия, и, какнеизвестно, стемжесозданнымтоном, которыйоннемогпонять, чтоэтобылоиневэтом.  — Что, конечно, немогу, ничего!

Input: Сила войска зависит от его духа
Raw_Output: Си ла вой ска зави си т от его ду ха нь ч щи и ее ", ж н . Она в ри , кроме его глаза , у правля я на меня ! Вы не по нрави лось меня ? И это у нее есть . — А вот ъ
Readable_output: Силавойсказависитотегодуханьчщииее", жн. Онаври, кромеегоглаза, управляянаменя! Вынепонравилосьменя? Иэтоунееесть.  — Авотъ


=== GENERATION LOG (Validation Phase) ===
Input: Все мысли, которые имеют огромные последствия
Raw_Output: Все мысли , которые име ют огром ные послед ствия и что вы дума ете , когда не при ве дут в ва го н до носи ть на них . — Что ж ты , не пла чи шь ? - Что же ка са ется до се ле
Readable_output: Всемысли, которыеимеютогромныепоследствияичтовыдумаете, когданеприведутввагондоноситьнаних.  — Чтожты, неплачишь? -Чтожекасаетсядоселе

Input: Сила войска зависит от его духа
Raw_Output: Си ла вой ска зави си т от его ду ха , как я за тру дня лась в верх по сти и не вырази л ее ни что же ство , но все еще х уже и с любопыт ством . — Как это вы могли бы при знать ?
Readable_output: Силавойсказависитотегодуха, какязатрудняласьвверхпостииневыразилееничтожество, новсеещехужеислюбопытством.  — Какэтовымоглибыпризнать?


=== GENERATION LOG (Validation Phase) ===
Input: Все мысли, которые имеют огромные последствия
Raw_Output: Все мысли , которые име ют огром ные послед ствия . — Я тоже не знаю , что вы меня знаете ... — По жал уй ста ... а я тебе - то у б ью ! В с ё это было уже до того , чтобы были по жар
Readable_output: Всемысли, которыеимеютогромныепоследствия.  — Ятоженезнаю, чтовыменязнаете. . .  — Пожалуйста. . . аятебе-тоубью! Всёэтобылоужедотого, чтобыбылипожар

Input: Сила войска зависит от его духа
Raw_Output: Си ла вой ска зави си т от его ду ха ми д . — Да , я знаю , что ты меня люби шь ... И опять она говорила : " Ну , и ди ко мне . С ме ш ны ря ли в ту ф ля х .
Readable_output: Силавойсказависитотегодухамид.  — Да, язнаю, чтотыменялюбишь. . . Иопятьонаговорила:"Ну, идикомне. Смешныряливтуфлях.


=== GENERATION LOG (Validation Phase) ===
Input: Все мысли, которые имеют огромные последствия
Raw_Output: Все мысли , которые име ют огром ные послед ствия им пера то ры и в ро де их в те сно е , но не об нару жи мо . — Не за будь те ... — Нет , нет ! - Д ва дцать тысяч , как он
Readable_output: Всемысли, которыеимеютогромныепоследствияимператорыивродеихвтесное, нонеобнаружимо.  — Незабудьте. . .  — Нет, нет! -Двадцатьтысяч, какон

Input: Сила войска зависит от его духа
Raw_Output: Си ла вой ска зави си т от его ду ха , со вет про би бы ва шей по чки . Не в чем дело ! — Да , — сказал он , и уже при ходили к ней . - Я не у знала вас , я знаю ,
Readable_output: Силавойсказависитотегодуха, советпробибывашейпочки. Невчемдело!  — Да,  — сказалон, иужеприходиликней. -Янеузналавас, язнаю,


=== GENERATION LOG (Validation Phase) ===
Input: Все мысли, которые имеют огромные последствия
Raw_Output: Все мысли , которые име ют огром ные послед ствия или т мо н ты от носи ться к нему . В место за да чей же вы ходил и не с пал . — Вы очень счастли в ли тера ту ре ц кого , — отвечал он .
Readable_output: Всемысли, которыеимеютогромныепоследствияилитмонтыотноситьсякнему. Вместозадачейжевыходилинеспал.  — Выоченьсчастливлитературецкого,  — отвечалон.

Input: Сила войска зависит от его духа
Raw_Output: Си ла вой ска зави си т от его ду ха ! В ч , в котором я по ехал . Он с читал и думал о своем про ме жу то чной гру дной ма ши ной , которая находи ла его . — Да , конечно , не было
Readable_output: Силавойсказависитотегодуха! Вч, вкоторомяпоехал. Онсчиталидумалосвоемпромежуточнойгрудноймашиной, котораянаходилаего.  — Да, конечно, небыло


=== GENERATION LOG (Validation Phase) ===
Input: Все мысли, которые имеют огромные последствия
Raw_Output: Все мысли , которые име ют огром ные послед ствия ми . А я сам по - наше ... — Я вас не понимаю ! Он при сел на сту л , от сте г нув над головой Григори я и с жа дно сти ю на помни в ему
Readable_output: Всемысли, которыеимеютогромныепоследствиями. Аясампо-наше. . .  — Яваснепонимаю! Онприселнастул, отстегнувнадголовойГригорияисжадностиюнапомнивему

Input: Сила войска зависит от его духа
Raw_Output: Си ла вой ска зави си т от его ду ха в своей ! В то у стало рас с и он , что ле жит не в мо ре ; а ма ни на столько , чтобы по казать себя , как во сне , - про би ло ,
Readable_output: Силавойсказависитотегодухавсвоей! Втоусталорассион, чтолежитневморе;аманинастолько, чтобыпоказатьсебя, каквосне, -пробило,


=== GENERATION LOG (Validation Phase) ===
Input: Все мысли, которые имеют огромные последствия
Raw_Output: Все мысли , которые име ют огром ные послед ствия ? — Вы не бу дете жить в душе , или я вам скажу . - А почему это вы дума ете ? С ле ва от него к нему при нес с ка шей . Я вот по ста
Readable_output: Всемысли, которыеимеютогромныепоследствия?  — Вынебудетежитьвдуше, илиявамскажу. -Апочемуэтовыдумаете? Слеваотнегокнемупринесскашей. Явотпоста

Input: Сила войска зависит от его духа
Raw_Output: Си ла вой ска зави си т от его ду ха ше ну ... какой стра ем ! Д еще до ст мгнове ная , да и не когда : так ве ж тебе в сердце . - А то вот что , - ото ро х лась она , как
Readable_output: Силавойсказависитотегодухашену. . . какойстраем! Дещедостмгновеная, даинекогда:таквежтебевсердце. -Атовотчто, -оторохласьона, как


=== GENERATION LOG (Validation Phase) ===
Input: Все мысли, которые имеют огромные последствия
Raw_Output: Все мысли , которые име ют огром ные послед ствия . Это был человек ф аль ш от сти к э т ры ? - Ты , конечно , с пал ками не ту , а все ж тебе на голову при ка жу . – Да что вы из
Readable_output: Всемысли, которыеимеютогромныепоследствия. Этобылчеловекфальшотстикэтры? -Ты, конечно, спалкаминету, авсежтебенаголовуприкажу. –Дачтовыиз

Input: Сила войска зависит от его духа
Raw_Output: Си ла вой ска зави си т от его ду ха наше ешь чь л з ве сне шки сов ! А чего тебе жал стало про не пла нка , что мы вы ехали из дому ... — Ну , ну - ди ж , и дите спа ть !
Readable_output: Силавойсказависитотегодуханашеешьчьлзвеснешкисов! Ачеготебежалсталопронепланка, чтомывыехалииздому. . .  — Ну, ну-диж, идитеспать!


=== GENERATION LOG (Validation Phase) ===
Input: Все мысли, которые имеют огромные последствия
Raw_Output: Все мысли , которые име ют огром ные послед ствия
Readable_output: Всемысли, которыеимеютогромныепоследствия

Input: Сила войска зависит от его духа
Raw_Output: Си ла вой ска зави си т от его ду ха стало бле крови чки ну лым ве тывал " про дело рас ... А про ти сты чь в всей ца сне чка л жа ! К тебе до слу ни Се щее не ма , что ли чего я
Readable_output: Силавойсказависитотегодухасталоблекровичкинулымветывал"проделорас. . . Апротистычьввсейцаснечкалжа! КтебедослуниСещеенема, чтоличегоя


=== GENERATION LOG (Validation Phase) ===
Input: Все мысли, которые имеют огромные последствия
Raw_Output: Все мысли , которые име ют огром ные послед ствия к . Но вдруг о ри ни ли ? — Я не знаю , как это хорошо было в жизни ! – вскри чал он , с из ум ле нием за гляды вая в глаза матери . " А
Readable_output: Всемысли, которыеимеютогромныепоследствияк. Новдругоринили?  — Янезнаю, какэтохорошобыловжизни! –вскричалон, сизумлениемзаглядываявглазаматери. "А

Input: Сила войска зависит от его духа
Raw_Output: Си ла вой ска зави си т от его ду ха ки сне и ло го кам мы нач ... Д дро ко тво слу во про ! Я по х не ма , за ка ты ша на себя реши мо ста в па ви ни ся в не ле
Readable_output: Силавойсказависитотегодухакиснеилогокаммынач. . . Ддрокотвослувопро! Япохнема, закатышанасебярешимоставпавинисявнеле


=== GENERATION LOG (Validation Phase) ===
Input: Все мысли, которые имеют огромные последствия
Raw_Output: Все мысли , которые име ют огром ные послед ствия ни в ле до вой бу н ту ски , а ре ни ро бле ства , ше ка , ра мо нов , как я й ца , — из - за б ви с ша гов , или
Readable_output: Всемысли, которыеимеютогромныепоследствиянивледовойбунтуски, аренироблества, шека, рамонов, какяйца,  — из-забвисшагов, или

Input: Сила войска зависит от его духа
Raw_Output: Си ла вой ска зави си т от его ду ха и дело по вы ка ца " стало сне и ки кла при ста чей в поло би ма мы сне вой сне ну ба шь - уже чка чего д со ем ста ка сту пол гло ри ма
Readable_output: Силавойсказависитотегодухаиделоповыкаца"сталоснеикиклапристачейвполобимамысневойсненубашь-ужечкачегодсоемстакаступолглорима

('./russian_lit_model_final/tokenizer_config.json',
 './russian_lit_model_final/special_tokens_map.json',
 './russian_lit_model_final/tokenizer.json')

попыталась вывести читабельный вывод генерации на валидации через readable_output. лучше это конечно убрать, т.к. только мешает нормально посмотреть ход обучения.

##### 6. Финальная генерация ответов на запросы

In [69]:
print("\n=== ИТОГОВАЯ ГЕНЕРАЦИЯ ОТВЕТОВ ===")
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
model.eval()

for prompt in test_prompts:
    inputs = fast_tokenizer(prompt, return_tensors="pt", return_token_type_ids=False).to(device)
    with torch.no_grad():
        outputs = model.generate(
            **inputs, 
            max_new_tokens=50, 
            do_sample=True, 
            temperature=0.2,       
            top_k=40,
            top_p=0.5,
            repetition_penalty=1.2, 
            no_repeat_ngram_size=2,
            pad_token_id=fast_tokenizer.pad_token_id,
            eos_token_id=fast_tokenizer.eos_token_id
        )
    text = fast_tokenizer.decode(outputs[0], skip_special_tokens=True)
    # clean_text_view = text.replace(" ", "").replace(",", ", ").replace(".", ". ").replace("!", "! ").replace("?", "? ").replace("—", " — ")
    
    print(f"PROMPT: {prompt}")
    print(f"OUTPUT: {text}")
    print("-" * 60)

=== ИТОГОВАЯ ГЕНЕРАЦИЯ ОТВЕТОВ ===
PROMPT: Все мысли, которые имеют огромные последствия
OUTPUT: Все мысли , которые име ют огром ные послед ствия ни в чем не по сти жи мо . — Я не знаю , что ты говори шь ! - А я так думаю : " Не ужели вы дума ете , как он сам винова т ?" Он ъ был ъ въ нем ъ и на г рѣ лъ
------------------------------------------------------------
PROMPT: Сила войска зависит от его духа
OUTPUT: Си ла вой ска зави си т от его ду ха стало стало про стала не пом ма ко про м в ше л сто ! — Я по зи , как вы дума ешь , я вас люблю , и все это вздо р . - А ты чего знаешь ? В то время как он под ходил к двери
------------------------------------------------------------
PROMPT: Мысль о том, что он принес страдания
OUTPUT: Мы с ль о том , что он при нес стра дания и по просил его . — Я не знаю , как ты дума ешь , — сказал он , у казы вая на пле чи . - А вот я тебе скажу : " Не ужели вы не вери те в бе д ную минуту ?" Он был очень до
------------------------------------------------------------
PROMPT: Человек сознает себя свободным
OUTPUT: Че лове к со знает себя свобо дным ди ди чи - го сти . — Да , я не понимаю , как это дела ет . И вот , по крайней мере , в этот раз , когда он про ходил мимо , она за ним алась его же ной и была та кою , что он
------------------------------------------------------------
PROMPT: Что бы ни случилось, я всегда буду
OUTPUT: Что бы ни случилось , я всегда буду . — А вы , князь , в самом деле ? - Не ужели так ? – Я не знаю , – сказал он , и дя за ним , чтобы не было . Он был очень бле ден , но все же при вле ка ет его к себе
------------------------------------------------------------
PROMPT: Любовь мешает смерти
OUTPUT: Лю бо вь ме ша ет смерти бы са бы бы на бы ле - с го ду бри б ща . — Я ж - то я ле ю , что он не может быть в пре фе и что я должен за да вить его . Он ъ не знает ъ , какъ онъ м
------------------------------------------------------------
PROMPT: Нет, жизнь не кончена
OUTPUT: Нет , жизнь не кон че на го - восто му , а в гу са ры х , с сы па нных в пе нь и це . — Да , я знаю , что это такое ? — Я очень ра да , — сказал он . Он был очень до во лен тем ,
------------------------------------------------------------
PROMPT: Всякая мысль, даже самая простая
OUTPUT: В ся кая мысль , даже сама я про стая . — Да ведь я и знал , что ты не хочешь сказать этого ? - А вот это вы , господин офицер , на пи лись ... - Ну , а как же ? Он был в бе лом , бле дный , с чер ными у си ками
------------------------------------------------------------
PROMPT: Война не любезность, а самое гадкое дело
OUTPUT: Во й на не любез ность , а самое га д кое дело в ко сти к вам по ва ря ка , то и ве ль мо жа ! — Да , я очень рад . - А ты что же ? Он был о дет в чер ную ту чу ю грудь ю , но с держа нно - бле дный
------------------------------------------------------------
PROMPT: Чтобы жить честно
OUTPUT: Что бы жить че стно е того р би е я серди из е го е ! — Я вы з ю же # е в чи е , как и во вся кого ви ли о ло ги ля й . - А вот что , - сказал он , не зная , что
------------------------------------------------------------

У модели получился относительно неплохой лосс к концу обучения - 2.94290 на тренировочном и 3.832294 на валидационном наборах. Была применена ранняя остановка обучения, чтобы модель не переобучалась. 
При генерации мы получаем нормальный и ожидаемый результат для pretrain. Ввиду маленького размера словаря BPE, модель вынуждена оперировать слогами, что может приводить к появлению "артефактов". Когда модель не уверена, она начинает перебирать наиболее вероятные слоги. Однако, модель хорошо выучила пунктуацию, стиль обращений, что означает, что модель научилась структуре языка. Это главное требование, которого мы добивались в pretrain-стадии обучения модели

#### SFT

##### 1. Подготовка датасета

In [18]:
raw_dataset = load_dataset("d0rj/alpaca-cleaned-ru")
raw_dataset

DatasetDict({
    train: Dataset({
        features: ['input', 'instruction', 'output'],
        num_rows: 51760
    })
})

In [24]:
# приведение к диалоговому формату
SYSTEM_PROMPT = "Ты — полезный, вежливый и русскоязычный ассистент."

def to_dialog(example):
    user_text = example["instruction"]
    if example.get("input"):
        user_text = user_text + "\n" + example["input"]

    return {
        "system": SYSTEM_PROMPT,
        "user": user_text.strip(),
        "assistant": example["output"].strip()
    }

dialog_dataset = raw_dataset["train"].map(
    to_dialog,
    remove_columns=raw_dataset["train"].column_names
)

Map: 100%|██████████| 51760/51760 [00:02<00:00, 19236.04 examples/s]

In [25]:
# деление на подвыборки
dataset = dialog_dataset.train_test_split(test_size=0.1, seed=42)
tmp = dataset["test"].train_test_split(test_size=0.5, seed=42)

train_ds = dataset["train"]
val_ds   = tmp["train"]
test_ds  = tmp["test"]

len(train_ds), len(val_ds), len(test_ds)

(46584, 2588, 2588)

In [26]:
# дедупликация данных
def example_hash(ex):
    text = ex["user"] + ex["assistant"]
    return hashlib.md5(text.encode("utf-8")).hexdigest()

def remove_overlap(train, *others):
    other_hashes = set()
    for ds in others:
        for ex in ds:
            other_hashes.add(example_hash(ex))

    filtered = [
        ex for ex in train
        if example_hash(ex) not in other_hashes
    ]
    return Dataset.from_list(filtered)

In [27]:
train_ds = remove_overlap(train_ds, val_ds, test_ds)

In [28]:
# внутренняя дедупликация
def fast_deduplicate(ds, max_len=200):
    seen = set()
    unique = []

    for ex in ds:
        key = (
            ex["user"][:max_len],
            ex["assistant"][:max_len]
        )
        if key not in seen:
            seen.add(key)
            unique.append(ex)

    return Dataset.from_list(unique)

In [29]:
train_ds = fast_deduplicate(train_ds)
val_ds   = fast_deduplicate(val_ds)
test_ds  = fast_deduplicate(test_ds)

len(train_ds), len(val_ds), len(test_ds)

(46574, 2588, 2588)

##### 2. Дообучение модели

In [30]:
model_name = "Qwen/Qwen2.5-0.5B"

tokenizer = AutoTokenizer.from_pretrained(
    model_name,
    trust_remote_code=True
)
tokenizer.pad_token = tokenizer.eos_token

In [32]:
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    dtype=torch.float16,
    device_map="auto",
    trust_remote_code=True
)

In [33]:
lora_config = LoraConfig(
    r=8,
    lora_alpha=16,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
    target_modules=[
        "q_proj", "k_proj", "v_proj",
        "o_proj", "gate_proj", "up_proj", "down_proj"
    ]
)

In [34]:
model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

trainable params: 4,399,104 || all params: 498,431,872 || trainable%: 0.8826

In [35]:
# форматирование диалога для SFTTrainer
def format_dialog(example):
    return (
        f"<|system|>\n{example['system']}\n"
        f"<|user|>\n{example['user']}\n"
        f"<|assistant|>\n{example['assistant']}"
    )

In [37]:
# параметры обучения
training_args = TrainingArguments(
    output_dir="./qwen2.5-ru-sft-lora",
    num_train_epochs=3,
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    gradient_accumulation_steps=8,
    learning_rate=2e-5,
    warmup_ratio=0.1,
    lr_scheduler_type="cosine",
    fp16=True,
    logging_steps=50,
    eval_strategy="steps",
    eval_steps=500,
    save_steps=500,
    save_total_limit=2,
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none"
)

In [43]:
trainer = SFTTrainer(
    model=model,
    processing_class=tokenizer,
    train_dataset=train_ds,
    eval_dataset=val_ds,
    formatting_func=format_dialog,
    # max_length=1024,
    args=training_args,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)]
)

/home/ubuntu/.local/lib/python3.10/site-packages/transformers/training_args.py:2111: FutureWarning: `--push_to_hub_token` is deprecated and will be removed in version 5 of 🤗 Transformers. Use `--hub_token` instead.
  warnings.warn(
Applying formatting function to train dataset:   0%|          | 0/46574 [00:00<?, ? examples/s]

Applying formatting function to train dataset: 100%|██████████| 46574/46574 [00:02<00:00, 18585.91 examples/s]
Adding EOS to train dataset: 100%|██████████| 46574/46574 [00:02<00:00, 17957.64 examples/s]
Tokenizing train dataset: 100%|██████████| 46574/46574 [00:32<00:00, 1426.71 examples/s]
Truncating train dataset: 100%|██████████| 46574/46574 [00:00<00:00, 171664.26 examples/s]
Applying formatting function to eval dataset: 100%|██████████| 2588/2588 [00:00<00:00, 20965.93 examples/s]
Adding EOS to eval dataset: 100%|██████████| 2588/2588 [00:00<00:00, 17818.69 examples/s]
Tokenizing eval dataset: 100%|██████████| 2588/2588 [00:01<00:00, 1484.33 examples/s]
Truncating eval dataset: 100%|██████████| 2588/2588 [00:00<00:00, 435868.08 examples/s]
The model is already on multiple devices. Skipping the move to device specified in `args`.

In [ ]:
trainer.train()

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

##### 3. Оценка адекватности генерации

In [ ]:
questions_rus = [
    "сколько планет в нашей солнечной системе?",
    "расскажи стих",
    "когда собирать крыжовник?",
    "Как быстро выучить новый язык?"
  ]

In [ ]:
def generate_answer(question):
    prompt = (
        "<|system|>\nТы — полезный русскоязычный ассистент.\n"
        "<|user|>\n" + question + "\n"
        "<|assistant|>\n"
    )

    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    with torch.no_grad():
        output = model.generate(
            **inputs,
            max_new_tokens=200,
            do_sample=True,
            top_p=0.9,
            temperature=0.7
        )

    return tokenizer.decode(output[0], skip_special_tokens=True)

In [ ]:
for q in questions_rus:
    print("=" * 80)
    print("QUESTION:", q)
    print("ANSWER:")
    print(generate_answer(q))